---
- name: Pre-reqs for ansible to run
  hosts: all
  gather_facts: false
  become: yes
  pre_tasks:
    - raw: test -e /usr/bin/python || ( yum -y update && yum install -y python-minimal )

- name: Build GPDB Master node.
  hosts: all
  become: true
  tasks:
  - name: Scriptrunners group
    group:
      name: scriptrunners
      system: yes

  - name: Create wherescape user
    user:
      name: wherescape
      group: scriptrunners

  - name: Make directory structure
    file:
      path: /{{ item }}
      state: directory
      mode: 0775
      recurse: yes
      owner: wherescape
      group: scriptrunners
    with_items:
      - u01
      - u01/wherescape_data
      - u01/wherescape_data/scripts
      - u01/EF
      - u01/EF/master
      - u01/EF/data
      - u02
      - u02/carrier_portal_export
      - u02/carrier_portal_export/logs
      - u02/s4
      - u02/s4/s4
      - u02/s4/s4/data
      - u02/s4/s4/data/xml
      - u02/s4/data
      - u02/s4/data/xml_modified
      - u02/s4/data/zipfiles
      - u02/s4/scripts
      - u02/s4/scripts/logs
      - u02/nbtc
      - u02/nbtc/data
      - u02/EF
      - u02/ssm
      - u02/ssm/data
      - u02/ssm/data/manual
      - u02/ssm/scripts
      - home/wherescape/prod

  - file:
      src: /u01/EF
      dest: /EF
      force: yes
      owner: wherescape
      group: scriptrunners
      state: link

  - name: Symlink script files
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      force: yes
      state: link
      owner: wherescape
      group: scriptrunners
    with_items:
      - { src: '/u01/EF/data', dest: '/u01/EF'}
      - { src: '/u01/EF/master/EF', dest: '/u01/EF'}
      - { src: '/home/wherescape/s4', dest: '/u02/s4'}
      - { src: '/home/wherescape/nbtc', dest: '/u02/nbtc'}
      - { src: '/home/wherescape/scripts', dest: '/u02/carrier_portal_export'}
      - { src: '/home/wherescape/EF', dest: '/u01/EF'}
      - { src: '/home/wherescape/prod/ssm', dest: '/u02/ssm'}

  - name: Yum Install Pre Dependencies
    yum: name={{ item }}
    with_items:
      - zip
      - ed
      - unzip
      - xfsdump
      - autoconf
      - popt-devel
      - zlib-devel
      - libaio-devel
      - mdadm
      - cryptsetup
      - cloud-utils
    become: true

  - name: PIP
    shell: curl https://bootstrap.pypa.io/get-pip.py | python
    args:
      creates: /bin/pip

  - name: AWS cli
    shell: pip install awscli
    args:
      creates: /bin/aws

  - name: Download cloudwatch logs agent
    get_url:
      url: https://s3.amazonaws.com//aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
      dest: /tmp/awslogs-agent-setup.py
      mode: "+x"

  - name: Cloudwatch logs config
    copy:
      dest: /tmp/cwlogs.conf
      content: |
        [general]
        state_file = /var/awslogs/state/agent-state
        [/var/log/syslog]
        file = /var/log/syslog
        log_group_name = /GPDB/system
        log_stream_name = {instance_id}
        datetime_format = %b %d %H:%M:%S
        [/GPDB/cloud-init]
        file = /var/log/cloud-init.log
        log_group_name = /GPDB/cloud-init
        log_stream_name = {instance_id}
        datetime_format = %Y-%m-%d %H:%M:%S,%f
        [/GPDB/cloud-init/output]
        file = /var/log/cloud-init-output.log
        log_group_name = /GPDB/cloud-init/output
        log_stream_name = {instance_id}
        datetime_format = %Y-%m-%d %H:%M:%S,%f
  - name: Install cloudwatch log agent
    environment:
      LC_ALL: C
    shell: /tmp/awslogs-agent-setup.py --region eu-west-2 --non-interactive -c /tmp/cwlogs.conf
    args:
      creates: /var/awslogs/etc/aws.conf

  - name: Copy cloudwatch logs starter
    copy:
      src: startcloudwatchlogs.sh
      dest: /usr/bin/startcloudwatchlogs.sh
      owner: root
      group: root
      mode: 0755

  - name: Make Cron Job to start awslogs with right region
    cron:
      name: Start awslogs
      special_time: reboot
      job: /usr/bin/startcloudwatchlogs.sh
